### ISSUE TITLE
Delete  cefview   ，crash

### ISSUE THREAD

**Issue by Liminglyq** [CefView/QCefView#2] opened 2021-04-13 06:10 UTC
void
QCefViewTest::onBtnNew()
{
  QDir dir = QCoreApplication::applicationDirPath();
  QString uri = QDir::toNativeSeparators(dir.filePath("QCefViewTestPage.html"));
  cefview = new CustomCefView(uri, this);
  // cefview = new CustomCefView("http://www.google.com/", this);
  ui.cefContainer->layout()->addWidget(cefview);
}

void
QCefViewTest::onBtnDelete()
{
  ui.cefContainer->layout()->removeWidget(cefview);
  delete cefview;
  cefview = nullptr;
}

crash  after delete  cefview

**Comment by xp19870106** [comment] 2021-04-26 09:24
@tishion when can this bug be solved? by the way, are u chinese? I saw you reply someone in chinese

**Comment by xp19870106** [comment] 2021-04-26 11:10
`void
CefViewBrowserHandler::CloseAllBrowsers(bool force_close)
{
  // If all browsers had been closed, then return
  std::unique_lock<std::mutex> lock(mtx_);
  if (!browser_count_) {
    return;
  }

  // Flip the closing flag
  is_closing_ = true;

  // Close all popup browsers if any
  if (!popup_browser_list_.empty()) {
    for (auto it = popup_browser_list_.begin(); it != popup_browser_list_.end(); ++it) {
      if (!(*it))
        continue;
      auto host = (*it)->GetHost();
      if (!host)
        continue;
      host->CloseBrowser(force_close);
    }
  }

  if (main_browser_) {
    // Request that the main browser close.
    auto host = main_browser_->GetHost();
    if (host)
      main_browser_->GetHost()->CloseBrowser(force_close);
  }

  if (!CefCurrentlyOn(TID_UI)) {
    // if we are not in browser main thread we need to wait for
    // all browsers to be closed, 
    while (browser_count_)
      cv_all_closed_.wait(lock);
  }
}`

you need to change the code as below, or the 
void CefViewBrowserHandler::OnBeforeClose(CefRefPtr<CefBrowser> browser)
won't be called

`void
CefViewBrowserHandler::CloseAllBrowsers(bool force_close)
{
  // If all browsers had been closed, then return
  std::unique_lock<std::mutex> lock(mtx_);
  if (!browser_count_) {
    return;
  }

  // Flip the closing flag
  is_closing_ = true;

  // Close all popup browsers if any
  if (!popup_browser_list_.empty()) {
    for (auto it = popup_browser_list_.begin(); it != popup_browser_list_.end(); ++it) {
      if (!(*it))
        continue;
      auto host = (*it)->GetHost();
      if (!host)
        continue;
      ::SetParent(host->GetWindowHandle(), NULL);
      host->CloseBrowser(force_close);
    }
  }

  if (main_browser_) {
    // Request that the main browser close.
    auto host = main_browser_->GetHost();
    if (host){
     ::SetParent(main_browser_->GetHost()->GetWindowHandle(), NULL);
      main_browser_->GetHost()->CloseBrowser(force_close);
    }
  }

  if (!CefCurrentlyOn(TID_UI)) {
    // if we are not in browser main thread we need to wait for
    // all browsers to be closed, 
    while (browser_count_)
      cv_all_closed_.wait(lock);
  }
}`

**Comment by xp19870106** [comment] 2021-04-26 11:11
`void
CefViewBrowserHandler::CloseAllBrowsers(bool force_close)
{
// If all browsers had been closed, then return
std::unique_lockstd::mutex lock(mtx_);
if (!browser_count_) {
return;
}

// Flip the closing flag
is_closing_ = true;

// Close all popup browsers if any
if (!popup_browser_list_.empty()) {
for (auto it = popup_browser_list_.begin(); it != popup_browser_list_.end(); ++it) {
if (!(*it))
continue;
auto host = (*it)->GetHost();
if (!host)
continue;
host->CloseBrowser(force_close);
}
}

if (main_browser_) {
// Request that the main browser close.
auto host = main_browser_->GetHost();
if (host)
main_browser_->GetHost()->CloseBrowser(force_close);
}

if (!CefCurrentlyOn(TID_UI)) {
// if we are not in browser main thread we need to wait for
// all browsers to be closed,
while (browser_count_)
cv_all_closed_.wait(lock);
}
}`

you need to change the code as below, or the
void CefViewBrowserHandler::OnBeforeClose(CefRefPtr browser)
won't be called

`void
CefViewBrowserHandler::CloseAllBrowsers(bool force_close)
{
// If all browsers had been closed, then return
std::unique_lockstd::mutex lock(mtx_);
if (!browser_count_) {
return;
}

// Flip the closing flag
is_closing_ = true;

// Close all popup browsers if any
if (!popup_browser_list_.empty()) {
for (auto it = popup_browser_list_.begin(); it != popup_browser_list_.end(); ++it) {
if (!(*it))
continue;
auto host = (*it)->GetHost();
if (!host)
continue;
::SetParent(host->GetWindowHandle(), NULL);
host->CloseBrowser(force_close);
}
}

if (main_browser_) {
// Request that the main browser close.
auto host = main_browser_->GetHost();
if (host){
::SetParent(main_browser_->GetHost()->GetWindowHandle(), NULL);
main_browser_->GetHost()->CloseBrowser(force_close);
}
}

if (!CefCurrentlyOn(TID_UI)) {
// if we are not in browser main thread we need to wait for
// all browsers to be closed,
while (browser_count_)
cv_all_closed_.wait(lock);
}
}`

@tishion

**Comment by tishion** [comment] 2021-04-27 01:25
i will try to fix this problems later (maybe in June or July), currently i have no time to work on this, sorry.

yes, I am Chinese.

**Comment by xp19870106** [comment] 2021-04-27 01:49
@tishion 太棒了，不用再说蛋疼的英语了。还有个问题，就是开了一个CefWiew之后，关闭再重新开一个会崩溃，我看了下，是QCefManager里面uninitializeCef里面的releaseCef()调用之后，再次调用initializeCef()里面的if (!CefInitialize(main_args, cef_settings_, app_, sandboxInfo))崩溃掉了，如果可以一起修复了吧。
辛苦啦！！

**Comment by tishion** [comment] 2021-05-03 06:18
这个问题属于已知设计问题，但是现在确实没时间去改。

**Comment by xp19870106** [comment] 2021-05-06 10:20
@tishion 可以禁用cefview吗？就是让鼠标交互无效

**Comment by xp19870106** [comment] 2021-05-08 12:38
@tishion 还有一个问题，就是我在创建qcefview的时候不指定url，后面调用navigatetourl方法，会崩溃，因为
 pQCefViewHandler_->GetBrowser()->GetMainFrame()->LoadURL(data);
这里拿到的GetBrowser为空，只有当页面已经显示后调用navigatetourl方法才正常

**Comment by stevezhougs** [comment] 2021-05-19 05:50
QCefViewTest,how to exit the app?
When I click close the QCefViewTest's windows,the app still running.

**Comment by Fishguys** [comment] 2021-08-18 06:37
> QCefViewTest,how to exit the app?
> When I click close the QCefViewTest's windows,the app still running.

when you close the QCefViewTest's windows, QCefViewTest's top level window
::SendMessage(hWnd, WM_CLOSE, 0, 0);

**Comment by tishion** [comment] 2022-01-06 14:26
Duplicate of #24

**Closed by tishion** 2022-01-06 14:26 UTC
Labels: bug
