### ISSUE TITLE
[BUG]: AltGr key modifier not working

### ISSUE THREAD

**Issue by Klarso-IvoBurkart** [CefView/QCefView#208] opened 2023-01-16 06:46 UTC
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
The AltGr key modifier is not working in CEFView-Widgets, making it impossible for some characters to be entered by keyboard depending on key layout. Example would be '[' or '@' on Germany layout.

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. Create a programm with a QCefView
2. Open google.com
3. Try to enter a character that needs AltGr
4. Character won't appear

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
All characters are inputable

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: OSR
 - OS & Version: Windows
 - Qt Version: 5.15.2
 - CEF Version: 102.0.10+gf249b2e+chromium-102.0.5005.115
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tishion** [comment] 2023-01-16 16:03
i believe this problem was caused by this piece of code
https://github.com/CefView/QCefView/blob/b7baf2094f2f01f2af19755b9660101b6930a11b/src/details/QCefViewPrivate.cpp#L708-L746

but need further investigating

**Comment by JohannesMunk** [comment] 2023-01-17 07:34
When you are investigating this, please also consider changing this line to support further flags/keys being set:

https://github.com/CefView/QCefView/blob/30c916aecc5d6662eef7529a312faa4f7ae54428/src/details/utils/KeyboardUtils.cpp#L432

For reference see:
https://bitbucket.org/chromiumembedded/cef/pull-requests/377

**Comment by tishion** [comment] 2023-01-21 09:11
@JohannesMunk @JohannesMunk   I think it will work now.

**Comment by JohannesMunk** [comment] 2023-01-21 11:21
@tishion Thank you for investigating!! Indeed {}, [] and @ work as expected! BUT: All other keys don't work properly anymore. If I press <A> it behaves like <Ctrl>+<A>. Most other characters wont appear, cursor keys don't work. I don't understand how your code change would cause this.

**Comment by tishion** [comment] 2023-01-21 11:25
oh crap!! I will look into it later.
________________________________

**Comment by tishion** [comment] 2023-01-21 11:28
> @tishion Thank you for investigating!! Indeed {}, [] and @ work as expected - `<AltGr>` seems to work! BUT: All other keys don't work properly anymore. If I press `<A>` it behaves like `<Ctrl>+<A>`. Most other characters wont appear, cursor keys don't work. I don't understand how your code change would cause this.

please refer to this PR
https://github.com/CefView/QCefView/pull/212

**Comment by JohannesMunk** [comment] 2023-01-21 11:34
I think I found it: Your return statement moved inside the if. If you move it back outside everything works as expected! Thx a lot!

**Comment by tishion** [comment] 2023-01-21 11:40
can you help to draft a PR to fix this?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tishion** [comment] 2023-01-21 12:59
Fixed and i am closing this. thanks

**Closed by tishion** 2023-01-21 13:00 UTC
Labels: bug
